# Generated by Django 3.2.9 on 2022-03-11 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyblogging', '0009_alter_blogmodel_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
