# Generated by Django 3.2.9 on 2022-03-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyblogging', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
