# Generated by Django 3.2.9 on 2022-03-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyblogging', '0012_rename_comment_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
