# Generated by Django 3.2.9 on 2022-03-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyblogging', '0014_comment_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='easyblogging.Category'),
        ),
    ]
