# Generated by Django 3.2.9 on 2022-03-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyblogging', '0015_auto_20220315_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Register_date', models.DateField()),
                ('Satisfaction_level', models.CharField(choices=[('excellent', 'excellent'), ('good', 'good'), ('ok', 'ok'), ('bad', 'bad')], default='good', max_length=30)),
                ('feedback', models.TextField(blank=True, max_length=300)),
            ],
        ),
    ]
