# Generated by Django 3.2.9 on 2022-03-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyblogging', '0016_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
