# Generated by Django 3.2.9 on 2022-03-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyblogging', '0017_blogmodel_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='publish',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
